CREATE TABLE public.usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre CHARACTER VARYING NULL,
    apellidos CHARACTER VARYING NOT NULL,
    correo CHARACTER VARYING NOT NULL,
    password CHARACTER VARYING NOT NULL,
    rol CHARACTER VARYING NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario)
);

CREATE TABLE public.autoescuelas (
    id_autoescuela BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre TEXT NOT NULL,
    telefono CHARACTER VARYING NOT NULL,
    precio_practica DOUBLE PRECISION NOT NULL,
    id_administrador BIGINT NULL,
    CONSTRAINT autoescuelas_pkey PRIMARY KEY (id_autoescuela),
    CONSTRAINT autoescuelas_id_administrador_fkey FOREIGN KEY (id_administrador) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
);

CREATE TABLE public.profesores (
    id_profesor BIGINT NOT NULL,
    id_autoescuela BIGINT NULL,
    CONSTRAINT profesores_pkey PRIMARY KEY (id_profesor),
    CONSTRAINT profesores_id_profesor_fkey FOREIGN KEY (id_profesor) REFERENCES usuarios (id_usuario)
);

CREATE TABLE public.alumnos (
    id_alumno BIGINT NOT NULL,
    id_autoescuela BIGINT NOT NULL,
    CONSTRAINT alumnos_pkey PRIMARY KEY (id_alumno),
    CONSTRAINT alumnos_id_alumno_fkey FOREIGN KEY (id_alumno) REFERENCES usuarios (id_usuario)
);

CREATE TABLE public.practicas (
    id_profesor BIGINT NOT NULL,
    id_alumno BIGINT NULL,
    fecha DATE NOT NULL,
    hora TIME WITHOUT TIME ZONE NOT NULL,
    tipo CHARACTER VARYING NOT NULL,
    id_practica BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT practicas_pkey PRIMARY KEY (id_profesor, fecha, hora, id_practica),
    CONSTRAINT practicas_id_alumno_fkey FOREIGN KEY (id_alumno) REFERENCES alumnos (id_alumno) ON DELETE SET NULL,
    CONSTRAINT practicas_id_profesor_fkey FOREIGN KEY (id_profesor) REFERENCES profesores (id_profesor) ON DELETE CASCADE
);

CREATE TABLE public.comunicados (
    id_comunicado BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo CHARACTER VARYING NOT NULL,
    mensaje TEXT NOT NULL,
    fecha DATE NOT NULL,
    id_profesor BIGINT NOT NULL,
    CONSTRAINT comunicados_pkey PRIMARY KEY (id_comunicado),
    CONSTRAINT comunicados_id_profesor_fkey FOREIGN KEY (id_profesor) REFERENCES profesores (id_profesor) ON DELETE CASCADE
);

ALTER TABLE profesores
    ADD CONSTRAINT profesores_id_autoescuela_fkey FOREIGN KEY (id_autoescuela) REFERENCES autoescuelas (id_autoescuela) ON DELETE CASCADE;

ALTER TABLE alumnos
    ADD CONSTRAINT alumnos_id_autoescuela_fkey FOREIGN KEY (id_autoescuela) REFERENCES autoescuelas (id_autoescuela) ON DELETE CASCADE;

